name: Deploy Flask via SSM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      INSTANCE_ID: i-00fc0cd34fafddb03
      REGION: ap-northeast-2
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Deploy via SSM
        run: |
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set region "$AWS_REGION"

          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Flask App" \
            --instance-ids "$INSTANCE_ID" \
            --parameters 'commands=[
              "cd /home/ubuntu/flask-app",
              "docker stop flask-app || true",
              "docker rm flask-app || true",
              "docker build -t flask-app .",
              "docker run -d -p 5000:5000 flask-app"
            ]' \
            --region "$REGION" \
            --output text

# force trigger
